### ISSUE TITLE
fails if shell is tcsh

### ISSUE THREAD

**Issue by qmwugbt112** [yeban/oswitch#15] opened 2015-01-22 11:04 UTC
Having got over the sudo problem, I had further issues with the 

bundle exec bin/switch biolinux

command.

Here are the last few warning/error messages

Get:5 http://archive.ubuntu.com/ubuntu/ trusty/universe kbuild amd64 1:0.1.9998svn2695+dfsg-1 [539 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty/multiverse virtualbox-guest-source all 4.3.10-dfsg-1 [550 kB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 2,954 kB in 1s (2,122 kB/s)
Selecting previously unselected package dkms.
(Reading database ... 197222 files and directories currently installed.)
Preparing to unpack .../dkms_2.2.0.3-1.1ubuntu5.14.04_all.deb ...
Unpacking dkms (2.2.0.3-1.1ubuntu5.14.04) ...
Selecting previously unselected package virtualbox-guest-utils.
Preparing to unpack .../virtualbox-guest-utils_4.3.10-dfsg-1_amd64.deb ...
Unpacking virtualbox-guest-utils (4.3.10-dfsg-1) ...
Selecting previously unselected package virtualbox-guest-dkms.
Preparing to unpack .../virtualbox-guest-dkms_4.3.10-dfsg-1_all.deb ...
Unpacking virtualbox-guest-dkms (4.3.10-dfsg-1) ...
Selecting previously unselected package virtualbox-guest-x11.
Preparing to unpack .../virtualbox-guest-x11_4.3.10-dfsg-1_amd64.deb ...
Unpacking virtualbox-guest-x11 (4.3.10-dfsg-1) ...
Selecting previously unselected package kbuild.
Preparing to unpack .../kbuild_1%3a0.1.9998svn2695+dfsg-1_amd64.deb ...
Unpacking kbuild (1:0.1.9998svn2695+dfsg-1) ...
Selecting previously unselected package virtualbox-guest-source.
Preparing to unpack .../virtualbox-guest-source_4.3.10-dfsg-1_all.deb ...
Unpacking virtualbox-guest-source (4.3.10-dfsg-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up dkms (2.2.0.3-1.1ubuntu5.14.04) ...
Setting up virtualbox-guest-utils (4.3.10-dfsg-1) ...
Setting up kbuild (1:0.1.9998svn2695+dfsg-1) ...
Setting up virtualbox-guest-source (4.3.10-dfsg-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up virtualbox-guest-dkms (4.3.10-dfsg-1) ...
Loading new virtualbox-guest-4.3.10 DKMS files...
First Installation: checking all kernels...
dpkg: warning: version '*-*' has bad syntax: version number does not start with digit
It is likely that 3.16.7-tinycore64 belongs to a chroot's host
Setting up virtualbox-guest-x11 (4.3.10-dfsg-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for libc-bin (2.19-0ubuntu6.5) ...
Giving Google-Chrome a prod, if you have it installed
dpkg-query: no packages found matching google-chrome-*
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.103ubuntu4.2) ...
stat: cannot stat ‘/home/*’: No such file or directory

All done - your system is updated to Bio-Linux 8!
 ---> da806f472169
Removing intermediate container 48e963907708
Successfully built da806f472169
Illegal variable name.

**Comment by yeban** [comment] 2015-01-22 11:10
Looks like everything went fine till building BioLinux. Issue probably while running the resulting image in a container.

`Illegal variable name` isn't very helpful. Nothing just before or after that?

What's the output of `docker -v`?

**Comment by qmwugbt112** [comment] 2015-01-22 11:21
I have just changed my login shell from tcsh to bash and fired up terminal again.  

bundle exec bin/switch biolinux now seems to work, without the need for a reinstall.  See below

n56-170:~ rnichols$ echo $SHELL
/bin/bash
n56-170:~ rnichols$ cd switch
n56-170:switch rnichols$ boot2docker start
Waiting for VM and Docker daemon to start...
.o
Started.
Writing /Users/rnichols/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/rnichols/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/rnichols/.boot2docker/certs/boot2docker-vm/key.pem

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH=/Users/rnichols/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1

n56-170:switch rnichols$  export DOCKER_HOST=tcp://192.168.59.103:2376
n56-170:switch rnichols$  export DOCKER_CERT_PATH=/Users/rnichols/.boot2docker/certs/boot2docker-vm
n56-170:switch rnichols$  export DOCKER_TLS_VERIFY=1 n56-170:switch rnichols$ docker run hello-world
Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (Assuming it was not already locally available.)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

For more examples and ideas, visit:
 http://docs.docker.com/userguide/
n56-170:switch rnichols$ cd switch
-bash: cd: switch: No such file or directory
n56-170:switch rnichols$ ls ..
* New stuff
Applications
CLC_Data
CLCdatabases
Desktop
Documents
Downloads
Dropbox
Dropbox-personal
Functions.java
Java3D_and_JAI.dmg
Library
Movies
Music
Pictures
Public
Sites
VirtualBox VMs
data
deskUNPDF
fastaXO
github
newfile
normalgraph9.jar
parisdata.xls
profiles.bin
signat.htm
switch
ugbt112@frontend1.apocrita.hpc.qmul.ac.uk

n56-170:switch rnichols$ sudo gem install bundler
Password:

Successfully installed bundler-1.7.12
Parsing documentation for bundler-1.7.12
1 gem installed
n56-170:switch rnichols$ bundle install --path .gem
Resolving dependencies...
Using colorize 0.7.5
Using switch 0.0.1 from source at .
Using bundler 1.7.12
Your bundle is complete!
It was installed into ./.gem

n56-170:switch rnichols$ bundle exec bin/switch biolinux

################################################################################
You are now running: biolinux, in container: biolinux-5490.

Container is distinct from the shell your launched this container from. Changes
you make here will be lost unless it's made to one of the directories below:

 - /Volumes/Time Machine Backups
 - /Applications
 - /Applications (Mac OS 9)
 - /Desktop (Mac OS 9)
 - /Desktop Folder
 - /Developer
 - /Documents
 - /DraftANR2.4.07
 - /FRoot007973422
 - /HDY 2006 Q3 final.doc
 - /libpeerconnection.log
 - /Library
 - /MAU 1.1.2 Update Log
 - /NetWare Client Utilities
 - /Office X SR1 Updater Log
 - /paperTree_v5.doc
 - /SexChrPaperV10.doc
 - /SexChrPaperV12.doc
 - /sw
 - /untitled folder
 - /Updaters
 - /User Guides And Information
 - /User Information
 - /Value Pack
 - /Users/rnichols

It's possible you may not be able to write to one or more directories above,
but it should be possible to read data from all. Home directory is often the
safest to write to.

Press Ctrl-D or type 'exit' to go back.
################################################################################

rnichols@biolinux-5490:~/switch$ whereis blastall
blastall: /usr/bin/blastall /usr/bin/X11/blastall /usr/share/man/man1/blastall.1.gz
rnichols@biolinux-5490:~/switch$

**Comment by yeban** [comment] 2015-01-22 11:40
That's a bug then. Thanks. Expected behaviour is to give you 'bash', if login shell is not 'bash|zsh|fish'.

**Comment by yeban** [comment] 2015-02-17 07:58
Should work with `tcsh` now. Can you give it a try?

**Comment by yeban** [comment] 2015-02-24 14:37
I will close it then. I am able to get it to work if shell is `tcsh`.

**Closed by yeban** 2015-02-24 14:37 UTC

**Comment by qmwugbt112** [comment] 2015-02-24 17:04
Dear Anurag

Did I say, I made my default login shell bash so I can’t test it right away.  
I could try and re-engineer the problem if it is vital.

R


Richard Nichols
Professor of Genetics
http://goo.gl/5oUP2J
